name: Setup Project
description: Prepare and install the Node-related tooling

inputs:
  bun-version:
    description: Version of Bun to use
    default: latest

  node-version:
    description: Version of Node to use
    default: 20.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Install dependencies
      run: bun install
      shell: bash
